import { 
  LayoutDashboard, 
  MessageSquare, 
  Upload, 
  History, 
  Settings, 
  Users, 
  Briefcase, 
  TrendingUp, 
  Megaphone, 
  Share2, 
  Lightbulb, 
  Code, 
  UserPlus, 
  FileText, 
  Network, 
  Database, 
  Wand2, 
  BookOpen, 
  ShoppingCart, 
  ShieldCheck, 
  Zap, 
  GraduationCap, 
  HelpCircle, 
  BarChart3, 
  Layers
} from "lucide-react";

export const AGENTS = [
  { id: "meeting-summary", name: "Meeting Summary", icon: FileText, description: "Summarize meetings, extract action items, and draft emails." },
  { id: "sales-assistant", name: "AI Sales Assistant", icon: Briefcase, description: "Generate sales pitches and strategies to close deals." },
  { id: "financial-analyst", name: "AI Financial Analyst", icon: TrendingUp, description: "Analyze financial data, metrics, and forecasts." },
  { id: "marketing-campaign", name: "AI Marketing Agent", icon: Megaphone, description: "Design comprehensive marketing campaigns and goals." },
  { id: "social-media-manager", name: "AI Social Media Manager", icon: Share2, description: "Plan and create content for social media platforms." },
  { id: "business-strategy", name: "AI Business Strategy", icon: Lightbulb, description: "Provide strategic advice and business roadmaps." },
  { id: "code-review", name: "AI Code Review", icon: Code, description: "Review code for issues, security, and improvements." },
  { id: "hr-assistant", name: "AI HR Assistant", icon: UserPlus, description: "Assist with HR tasks, recruitment, and employee relations." },
  { id: "document-generator", name: "AI Document Generator", icon: FileText, description: "Generate structured documents and content." },
  { id: "knowledge-graph", name: "AI Knowledge Graph", icon: Network, description: "Extract entities and relationships from text." },
  { id: "data-cleaning", name: "AI Data Cleaning", icon: Database, description: "Suggest steps to clean and format raw data." },
  { id: "prompt-engineering", name: "AI Prompt Engineer", icon: Wand2, description: "Improve and optimize AI prompts for better results." },
  { id: "research-summarizer", name: "AI Research Summarizer", icon: BookOpen, description: "Summarize research papers and academic content." },
  { id: "product-recommendation", name: "AI Product Recommendation", icon: ShoppingCart, description: "Recommend products based on user profiles." },
  { id: "compliance-policy", name: "AI Compliance & Policy", icon: ShieldCheck, description: "Check content for compliance and policy violations." },
  { id: "personal-productivity", name: "AI Personal Productivity", icon: Zap, description: "Help with goal setting, scheduling, and tips." },
  { id: "training-content", name: "AI Training Generator", icon: GraduationCap, description: "Create training modules and educational material." },
  { id: "interview-question", name: "AI Interview Generator", icon: HelpCircle, description: "Generate interview questions and evaluation criteria." },
  { id: "business-report", name: "AI Business Report", icon: BarChart3, description: "Generate detailed business reports and summaries." },
  { id: "multi-agent-research", name: "Multi-Agent Research", icon: Layers, description: "Coordinate multiple agents for complex research tasks." },
];

export const NAV_ITEMS = [
  { id: "dashboard", name: "Dashboard", icon: LayoutDashboard, path: "/dashboard" },
  { id: "chat", name: "Chat", icon: MessageSquare, path: "/chat" },
  { id: "upload", name: "File Upload", icon: Upload, path: "/upload" },
  { id: "history", name: "History", icon: History, path: "/history" },
  { id: "settings", name: "Settings", icon: Settings, path: "/settings" },
];
